### ISSUE TITLE
Excuse sir ,I meet some problems when i used the code

### ISSUE THREAD

**Issue by NINEONE6** [jbferet/prosail#1]
I try to run the code about Estimate vegetation properties from optical images ,but always give the warning that i need  use samller min_lambda about liquidSVM. I have read the reference about function (train_prosail_inversion),but i did not find the way to set the min_lambda parameters,could you tell me how to set values about this? Thank you very much!!!!!!

**Comment by jbferet** [comment]
hi @NINEONE6, 
yes indeed, this warning message can occur when runnng LiquidSVM. 
I developed a function to automatically adjust this value if the warning message occurs (message "Adjusting Lambda accordingly" would then be printed). 

Despite the message you should still get trained regression models as outputs of the function. 

The suboptimal lambda value may result in lower performances of the regression model, but in practice, it seemed to work ok, even after this warning message.

I will try to add an option for users to add min_lambda values of their choice in a next version, but this means users will also need to put their hands in LiquidSVM to make sure they know what they are doing. 
Thank you for reporting this issue.
jean-Baptiste
